services:
  dev-test:
    build: .
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    command: ["cargo", "test", "--workspace", "--locked"]

  dev-run:
    build: .
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    cap_add: [NET_RAW]
    command: ["cargo", "run", "--locked", "--", "--config", "amitoki.toml"]

volumes:
  cargo-cache:
  target-cache:
