export const labels = {
  navigation: "画面",
  hex: "Hex",
  pipeline: "パイプライン",
  packets: "パケット解析",
  operations: "稼働状況",
  unavailable: "本体に接続できません",
  running: "稼働中",
  open: "PCAPを開く",
  analyzing: "解析中",
  capture: "PCAP",
  empty: "PCAPを選択してください",
  packet: "パケット",
  time: "収集時刻",
  type: "種類",
  length: "長さ",
  outcome: "判定",
  rejected: "拒否",
  failed: "エラー",
  dropped: "破棄",
  modified: "加工",
  passed: "通過",
  input: "Input packet",
  output: "Output packet",
  noOutput: "出力なし",
  previous: "前へ",
  next: "次へ",
  limit: "先頭1,000件",
  source: "再生元",
  plugin: "プラグイン",
  policy: "on_error",
  routes: "経路",
  required: "必須チェック",
  postcheck: "加工後検証 / 配送管理",
  replay: "再生構成",
  active: "稼働中の構成",
  outputTo: "送信予定",
  noTerminal: "送信先なし",
  queued: "待機",
  published: "送信",
  failures: "障害",
  captureCount: "収集",
  injected: "注入",
  filtered: "フィルタ",
  retry: "再試行",
  impaired: "送受信の一部停止",
  unknown: "未取得",
  events: "イベント",
  noEvents: "イベントなし",
  connected: "本体接続",
  disconnected: "本体切断",
  generation: "世代",
  reload: "Pipeline更新",
  preview: "先頭256バイト",
  login: "起動時に表示されたURLを開いてください",
  requestFailed: "読み込みに失敗しました",
  tooLarge: "PCAPは16MiB以内にしてください",
};
